const fs = require('fs');
const data = JSON.parse(fs.readFileSync('run-summary-embedded.json', 'utf8'));
console.log('=== FULL SUMMARY TOP LEVEL ===');
console.dir(Object.keys(data));
console.log('\n=== stopReason, commits, todos ===');
console.log({stopReason: data.stopReason, commits: data.commits, totalTodos: data.totalTodos, skipped: data.skippedTodos, stale: data.staleEvents, files: data.filesChanged});
console.log('\n=== RCA ===');
console.dir(data.rca);
console.log('\n=== HealthScore ===');
console.dir(data.healthScore);
console.log('\n=== Contract (first 2 criteria) ===');
console.dir(data.contract?.criteria?.slice(0,2));
console.log('\n=== Per agent stats (index, turns, tokensIn, commits, rejected) ===');
data.agents.forEach(a => console.log(  : turns= in= commits= rej=));
console.log('\n=== Transcript length in summary ===');
console.log('transcript entries:', data.transcript?.length || 0);
