// 2026-05-02 (deliverables initiative): every discussion preset
// produces a transcript today; only blackboard produces a portable
// artifact (the worker commits + summary.json). This module provides
// a shared way for the discussion runners (Council, MoA, MapReduce,
// OW, OW-Deep, Stigmergy, DebateJudge) to write a structured
// markdown deliverable to the clone — something the user can paste
// into a PR description, an issue, or a design doc.
//
// SHAPE (per-preset):
//   Each runner builds an array of DeliverableSection — title + body —
//   in whatever order makes sense for its preset. The shared writer
//   handles file naming, atomic write, transcript-entry posting, and
//   the metadata the UI uses to render a "Saved to X" bubble.
//
// FILE NAMING:
//   <clonePath>/deliverable-<preset>-<runId>-<iso>.md
//   Per-runId so multiple runs on the same clone don't overwrite each
//   other; iso suffix so back-to-back runs (same runId — wouldn't
//   happen in practice but defensive) still don't clash.
//
// FAILURE HANDLING:
//   Best-effort. Returns {ok: false, reason} on any write failure;
//   the calling runner posts a system message but continues. The
//   transcript still has the synthesis bubble — the deliverable file
//   is a bonus artifact, not the primary output.

import { writeFileSync, renameSync, mkdirSync } from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import type { SwarmEvent, TranscriptEntry } from "../types.js";
import type { Agent, AgentManager } from "../services/AgentManager.js";
import {
  type DerivedRubric,
  formatRubricMarkdown,
} from "./rubricPrePass.js";
import {
  runCriticPass,
  formatCriticMarkdown,
  extractNextActions,
  formatNextActionsMarkdown,
  type NextAction,
} from "./qualityPasses.js";

export interface DeliverableSection {
  /** Rendered as ## H2 in the markdown file. Keep short — section
   *  titles show up in the "table of contents" the writer auto-emits
   *  at the top. */
  title: string;
  /** The section's body. Markdown allowed (so subsections are OK).
   *  Empty string is fine; an empty section just renders as the H2
   *  followed by nothing. */
  body: string;
}

export interface DeliverableInput {
  /** Preset id ("moa", "council", etc). Used in the filename + the
   *  H1 line. */
  preset: string;
  /** Active run's id (orchestrator-minted). Used in the filename so
   *  multiple runs on the same clone don't collide. */
  runId: string;
  /** Where to write — typically cfg.localPath. */
  clonePath: string;
  /** Rendered as the H1 line. e.g. "Council synthesis", "MoA digest". */
  title: string;
  /** Optional one-line italic subtitle under the H1 (e.g. "3 drafters
   *  across 2 rounds against octocat/Hello-World"). */
  subtitle?: string;
  /** Ordered sections rendered in sequence. */
  sections: readonly DeliverableSection[];
}

export interface DeliverableResult {
  ok: boolean;
  /** Just the basename — "deliverable-moa-r1-2026-...md". UI renders
   *  this as the link text. */
  filename: string;
  /** Absolute path on disk. */
  fullPath: string;
  /** Total bytes written (informational). */
  bytes: number;
  /** Set when ok === false. */
  reason?: string;
  /** T1.3 (2026-05-04): basename of the sibling next-actions.json
   *  written alongside this deliverable. Absent when the JSON write
   *  failed (deliverable still ok). */
  nextActionsFile?: string;
  /** Number of action items extracted from the deliverable. 0 when
   *  the deliverable contained no recognizable action prose. */
  nextActionsCount?: number;
}

/** Pure markdown builder — exported separately for tests so the
 *  formatting can be locked in without touching the filesystem. */
export function buildDeliverableMarkdown(input: DeliverableInput): string {
  const lines: string[] = [];
  lines.push(`# ${input.title}`);
  if (input.subtitle && input.subtitle.trim().length > 0) {
    lines.push("");
    lines.push(`_${input.subtitle.trim()}_`);
  }
  lines.push("");
  lines.push(`> Generated by ollama_swarm preset: **${input.preset}** · run ${input.runId} · ${new Date().toISOString()}`);
  lines.push("");
  // Auto-TOC when there are 3+ sections — small reports don't need it.
  if (input.sections.length >= 3) {
    lines.push("## Contents");
    lines.push("");
    for (const s of input.sections) {
      lines.push(`- [${s.title}](#${anchor(s.title)})`);
    }
    lines.push("");
  }
  for (const s of input.sections) {
    lines.push(`## ${s.title}`);
    lines.push("");
    lines.push(s.body.trim().length > 0 ? s.body.trim() : "_(no content)_");
    lines.push("");
  }
  return lines.join("\n");
}

/** GitHub-flavored anchor slug for the auto-TOC links. Lowercased,
 *  spaces → hyphens, non-alphanumerics dropped (matches GFM's behavior
 *  closely enough for our 1-3 word section titles). */
function anchor(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

/** 2026-05-02 (quality levers #1+#2+#3): augment a runner's base
 *  sections with rubric (top), critic verdict (bottom), and extracted
 *  next-actions (bottom). Pure orchestration — calls into rubricPrePass
 *  + qualityPasses helpers. Best-effort: any failure (LLM call rejects,
 *  parse fails, etc.) silently falls back to the base sections, so the
 *  deliverable always lands with at least the original content.
 *
 *  Order of returned sections:
 *    1. Success criteria (rubric)
 *    2. ...the runner's base sections...
 *    3. Critic notes
 *    4. Next actions
 *
 *  Each augmentation is opt-in: pass `null` for rubric/criticAgent to
 *  skip that pass. Next-action extraction is always free (no LLM call). */
export async function runQualityPasses(input: {
  baseSections: readonly DeliverableSection[];
  rubric: DerivedRubric | null;
  criticAgent: Agent | null;
  manager: AgentManager;
}): Promise<DeliverableSection[]> {
  const { baseSections, rubric, criticAgent, manager } = input;
  // Compose the deliverable text the critic + extractor will read.
  // Use the same shape buildDeliverableMarkdown emits for sections so
  // the critic sees what the user will see.
  const baseText = baseSections
    .map((s) => `## ${s.title}\n\n${s.body}`)
    .join("\n\n");

  // Run the critic pass (when both agent + rubric provided).
  let criticSection: DeliverableSection | null = null;
  if (criticAgent && rubric) {
    try {
      const verdict = await runCriticPass({
        agent: criticAgent,
        manager,
        deliverable: baseText,
        rubric,
      });
      criticSection = {
        title: "Critic notes",
        body: formatCriticMarkdown(verdict),
      };
    } catch {
      // Best-effort — critic failure doesn't block the deliverable.
    }
  }

  // Extract next actions (pure parser, no LLM call — always run).
  const actions = extractNextActions(baseText);
  const nextActionsSection: DeliverableSection = {
    title: "Next actions",
    body: formatNextActionsMarkdown(actions),
  };

  // Compose final section list.
  const out: DeliverableSection[] = [];
  if (rubric) {
    out.push({ title: "Success criteria", body: formatRubricMarkdown(rubric) });
  }
  out.push(...baseSections);
  if (criticSection) out.push(criticSection);
  out.push(nextActionsSection);
  return out;
}

/** Convenience: write the deliverable AND post a system entry to the
 *  runner's transcript with a `deliverable` summary kind. Each runner
 *  used to have its own appendSystem variant; this lets them share
 *  one call site. The system message body names the file; the summary
 *  carries the metadata the UI uses to render a "Saved to X" bubble.
 *
 *  Returns the underlying writeDeliverable result so the caller can
 *  branch on success/failure. */
export function writeDeliverableAndEmit(
  input: DeliverableInput,
  ctx: {
    transcript: TranscriptEntry[];
    emit: (e: SwarmEvent) => void;
  },
): DeliverableResult {
  const result = writeDeliverable(input);
  const text = result.ok
    ? `Deliverable saved → ${result.filename}`
    : `Failed to write deliverable (${result.reason ?? "unknown"})`;
  const entry: TranscriptEntry = {
    id: randomUUID(),
    role: "system",
    text,
    ts: Date.now(),
    ...(result.ok
      ? {
          summary: {
            kind: "deliverable" as const,
            preset: input.preset,
            filename: result.filename,
            fullPath: result.fullPath,
            bytes: result.bytes,
            sectionTitles: input.sections.map((s) => s.title),
          },
        }
      : {}),
  };
  ctx.transcript.push(entry);
  ctx.emit({ type: "transcript_append", entry });
  return result;
}

/** Write the deliverable to disk via tmp + rename (atomic). Returns
 *  ok:false on filesystem failure; never throws.
 *
 *  T1.3 (2026-05-04): also writes a sibling `next-actions-<preset>-
 *  <runId>-<iso>.json` containing the structured action list extracted
 *  from the deliverable. Same atomic-write pattern; failure to write
 *  the sibling is non-fatal (the deliverable already landed). The
 *  JSON is what downstream tooling (forward-chain blackboard runs,
 *  GitHub Actions) consumes — markdown for humans, JSON for machines. */
export function writeDeliverable(input: DeliverableInput): DeliverableResult {
  const isoSafe = new Date().toISOString().replace(/[:.]/g, "-");
  const runIdShort = input.runId.slice(0, 8);
  const filename = `deliverable-${input.preset}-${runIdShort}-${isoSafe}.md`;
  const fullPath = path.join(input.clonePath, filename);
  const tmpPath = `${fullPath}.tmp`;
  const md = buildDeliverableMarkdown(input);
  try {
    mkdirSync(input.clonePath, { recursive: true });
    writeFileSync(tmpPath, md, "utf8");
    renameSync(tmpPath, fullPath);
  } catch (err) {
    return {
      ok: false,
      filename,
      fullPath,
      bytes: 0,
      reason: err instanceof Error ? err.message : String(err),
    };
  }
  // Sibling JSON write — best-effort; deliverable.ok stays true even if
  // JSON write fails. Surfaced via nextActionsFile when present.
  const jsonResult = writeNextActionsJson({
    preset: input.preset,
    runId: input.runId,
    runIdShort,
    isoSafe,
    clonePath: input.clonePath,
    deliverableMarkdown: md,
  });
  return {
    ok: true,
    filename,
    fullPath,
    bytes: md.length,
    ...(jsonResult.ok
      ? { nextActionsFile: jsonResult.filename, nextActionsCount: jsonResult.count }
      : {}),
  };
}

/** T1.3: structured next-actions JSON written alongside every deliverable.
 *  Pure JSON file at <clonePath>/next-actions-<preset>-<runId>-<iso>.json
 *  containing the extractNextActions output + run metadata. Downstream
 *  tooling (the forward-chain `chainTo:"blackboard"` flag, CI scripts,
 *  the eval harness) consumes this without re-parsing the markdown. */
export interface NextActionsJsonInput {
  preset: string;
  runId: string;
  runIdShort: string;
  isoSafe: string;
  clonePath: string;
  /** The full deliverable markdown — extractNextActions reads this. */
  deliverableMarkdown: string;
}

export interface NextActionsJsonResult {
  ok: boolean;
  filename: string;
  fullPath: string;
  count: number;
  reason?: string;
}

export function writeNextActionsJson(input: NextActionsJsonInput): NextActionsJsonResult {
  const filename = `next-actions-${input.preset}-${input.runIdShort}-${input.isoSafe}.json`;
  const fullPath = path.join(input.clonePath, filename);
  const tmpPath = `${fullPath}.tmp`;
  const actions = extractNextActions(input.deliverableMarkdown);
  const payload = {
    preset: input.preset,
    runId: input.runId,
    generatedAt: new Date().toISOString(),
    schemaVersion: 1,
    actions: actions.map((a: NextAction) => ({
      priority: a.priority,
      text: a.text,
      ...(a.source ? { source: a.source } : {}),
    })),
  };
  try {
    writeFileSync(tmpPath, JSON.stringify(payload, null, 2), "utf8");
    renameSync(tmpPath, fullPath);
    return { ok: true, filename, fullPath, count: actions.length };
  } catch (err) {
    return {
      ok: false,
      filename,
      fullPath,
      count: 0,
      reason: err instanceof Error ? err.message : String(err),
    };
  }
}
