// T199 (2026-05-04): test-scaffolding generator for blackboard's
// test-driven todo expansion (T198h replaces the prompt-only thin-cut
// with a real scaffolder).
//
// Detects the project's test framework + emits a stub failing test
// file that the planner can reference in its `verify:` clause.
// Languages: JS/TS only (vitest/jest/bun-test/node-test). Python /
// Rust / Go deferred — each needs its own framework detection +
// scaffold template.
//
// Pattern:
//   1. Probe for known test runner config (vitest.config.*, jest.config.*,
//      package.json scripts, tsconfig.json with vitest/jest deps)
//   2. Emit a stub test file at a sensible path (test/<topic>.test.ts
//      or src/<topic>.test.ts mirror) using the detected framework's
//      assertion API
//   3. Return the path + the stub content + the verify command
//      that should pass once the impl lands
//
// This is "scaffold + recommend"; the planner still constructs the
// todo. The scaffold gives the planner a concrete artifact to point
// at, so the verify clause is real-world executable instead of
// hypothetical.

import { promises as fs } from "node:fs";
import path from "node:path";

export type DetectedFramework =
  | "vitest"
  | "jest"
  | "bun-test"
  | "node-test"
  | "unknown";

export interface ScaffoldResult {
  framework: DetectedFramework;
  /** Suggested path for the stub test file. Caller can write or
   *  pass to the planner. */
  suggestedTestPath: string;
  /** Stub file content — a single failing test that asserts the
   *  feature exists. */
  stubContent: string;
  /** The verify command the planner should bake into its TODO's
   *  `verify:` clause (e.g. `npx vitest run test/foo.test.ts`). */
  verifyCommand: string;
}

/** Detect the test framework in use by reading package.json + scanning
 *  for config files. Pure-ish — only reads from disk; no network.
 *  Returns "unknown" when nothing matches; caller decides whether to
 *  emit a generic node:test scaffold or skip. */
export async function detectTestFramework(
  clonePath: string,
): Promise<DetectedFramework> {
  const pkgPath = path.join(clonePath, "package.json");
  let pkgRaw: string;
  try {
    pkgRaw = await fs.readFile(pkgPath, "utf8");
  } catch {
    return "unknown";
  }
  let pkg: { scripts?: Record<string, string>; devDependencies?: Record<string, string>; dependencies?: Record<string, string> };
  try {
    pkg = JSON.parse(pkgRaw);
  } catch {
    return "unknown";
  }
  const allDeps = { ...(pkg.devDependencies ?? {}), ...(pkg.dependencies ?? {}) };
  if (allDeps["vitest"]) return "vitest";
  if (allDeps["jest"]) return "jest";
  if (allDeps["@types/bun"] || allDeps["bun-types"]) return "bun-test";
  // node:test detection — no dep, but maybe a script using `--test`
  const scripts = pkg.scripts ?? {};
  for (const cmd of Object.values(scripts)) {
    if (cmd.includes("--test") || cmd.includes("node:test")) return "node-test";
    if (cmd.includes("vitest")) return "vitest";
    if (cmd.includes("jest")) return "jest";
    if (cmd.startsWith("bun test") || cmd.includes("bun test ")) return "bun-test";
  }
  // Probe config files
  for (const cfg of ["vitest.config.ts", "vitest.config.js", "vitest.config.mjs"]) {
    try {
      await fs.access(path.join(clonePath, cfg));
      return "vitest";
    } catch {
      // fall through
    }
  }
  for (const cfg of ["jest.config.ts", "jest.config.js", "jest.config.mjs", "jest.config.json"]) {
    try {
      await fs.access(path.join(clonePath, cfg));
      return "jest";
    } catch {
      // fall through
    }
  }
  return "unknown";
}

/** Build the stub test file content + verify command for a given
 *  framework + topic. `topic` is a short kebab-case name derived from
 *  the directive (e.g. "add-bcrypt-hashing" or "fix-off-by-one").
 *  Pure — exported for tests. */
export function buildScaffold(
  framework: DetectedFramework,
  topic: string,
  testPath: string,
): { stubContent: string; verifyCommand: string } {
  // T199: keep both cases — buildScaffold accepts arbitrary topic
  // text + slugifies for the test name. Uppercase preserved so the
  // generated test name is readable.
  const slug = topic.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_|_$/g, "");
  switch (framework) {
    case "vitest":
      return {
        stubContent: [
          "// T199 test scaffold (auto-generated by test-driven todo expansion).",
          "// This test SHOULD FAIL until the corresponding TODO is implemented.",
          "// The blackboard worker's verify gate uses it to confirm the work landed.",
          "",
          'import { describe, it, expect } from "vitest";',
          "",
          `describe("${topic}", () => {`,
          `  it("${slug}__placeholder — replace with real assertions matching the TODO", () => {`,
          "    // TODO: replace this assertion with one that PASSES only when the",
          "    // TODO's expected behavior is implemented. Until then this test",
          "    // intentionally fails so the verify gate has a real signal.",
          '    expect.fail("scaffolded placeholder — implement the TODO + replace this assertion");',
          "  });",
          "});",
        ].join("\n"),
        verifyCommand: `npx vitest run ${testPath}`,
      };
    case "jest":
      return {
        stubContent: [
          "// T199 test scaffold (auto-generated by test-driven todo expansion).",
          "// This test SHOULD FAIL until the corresponding TODO is implemented.",
          "",
          `describe("${topic}", () => {`,
          `  it("${slug}__placeholder — replace with real assertions matching the TODO", () => {`,
          "    // TODO: replace this assertion with one that PASSES only when the",
          "    // TODO's expected behavior is implemented.",
          '    throw new Error("scaffolded placeholder — implement the TODO + replace this assertion");',
          "  });",
          "});",
        ].join("\n"),
        verifyCommand: `npx jest ${testPath}`,
      };
    case "bun-test":
      return {
        stubContent: [
          "// T199 test scaffold (auto-generated by test-driven todo expansion).",
          "",
          'import { describe, it, expect } from "bun:test";',
          "",
          `describe("${topic}", () => {`,
          `  it("${slug}__placeholder — replace with real assertions matching the TODO", () => {`,
          '    expect("scaffold").toBe("implemented");',
          "  });",
          "});",
        ].join("\n"),
        verifyCommand: `bun test ${testPath}`,
      };
    case "node-test":
    default:
      return {
        stubContent: [
          "// T199 test scaffold (auto-generated by test-driven todo expansion).",
          "// This test SHOULD FAIL until the corresponding TODO is implemented.",
          "",
          'import { describe, it } from "node:test";',
          'import assert from "node:assert/strict";',
          "",
          `describe("${topic}", () => {`,
          `  it("${slug}__placeholder — replace with real assertions matching the TODO", () => {`,
          '    assert.fail("scaffolded placeholder — implement the TODO + replace this assertion");',
          "  });",
          "});",
        ].join("\n"),
        verifyCommand: `node --import tsx --test ${testPath}`,
      };
  }
}

/** Compose framework detection + scaffold. Returns null when the
 *  topic is empty / framework is unknown AND no node-test fallback
 *  is requested. Caller writes the stub to disk separately so this
 *  function stays pure. */
export async function scaffoldTestForTopic(input: {
  clonePath: string;
  topic: string;
  /** When framework detection returns "unknown", emit a node:test
   *  scaffold anyway. Default true (most repos benefit from a stub
   *  even without a configured runner). */
  fallbackToNodeTest?: boolean;
  /** Override the detected framework. Useful for tests + when caller
   *  knows better than the heuristic. */
  forceFramework?: DetectedFramework;
}): Promise<ScaffoldResult | null> {
  const topic = input.topic.trim();
  if (topic.length === 0) return null;
  const detected = input.forceFramework ?? (await detectTestFramework(input.clonePath));
  if (detected === "unknown" && input.fallbackToNodeTest === false) return null;
  const framework = detected === "unknown" ? "node-test" : detected;
  // Prefer test/ dir, fall back to src/ if test/ doesn't exist.
  const slug = topic.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  const testDirCandidates = ["test", "tests", "src/__tests__", "spec"];
  let testDir = "test";
  for (const candidate of testDirCandidates) {
    try {
      const stat = await fs.stat(path.join(input.clonePath, candidate));
      if (stat.isDirectory()) {
        testDir = candidate;
        break;
      }
    } catch {
      // fall through
    }
  }
  const ext =
    framework === "vitest" || framework === "jest" || framework === "bun-test"
      ? "test.ts"
      : "test.ts";
  const suggestedTestPath = path.posix.join(testDir, `${slug}.${ext}`);
  const { stubContent, verifyCommand } = buildScaffold(
    framework,
    topic,
    suggestedTestPath,
  );
  return {
    framework,
    suggestedTestPath,
    stubContent,
    verifyCommand,
  };
}
