#!/usr/bin/env bash
# Reads /tmp/smoke-tour-{label}-progress.json for each repo + the per-clone
# summary.json + .swarm-memory.jsonl artifacts, produces a Markdown digest at
# /tmp/smoke-tour-comparison.md. Idempotent — re-run any time to refresh.
set -uo pipefail

OUT=/tmp/smoke-tour-comparison.md
RUNS_DIR=/mnt/c/Users/kevin/Desktop/ollama_swarm/runs

REPOS=(
  "debate-tcg|/tmp/smoke-tour-debate-tcg-progress.json|/tmp/smoke-tour-debate-tcg.log|$RUNS_DIR/debate-tcg"
  "vocabmaster-android|/tmp/smoke-tour-vocabmaster-android-progress.json|/tmp/smoke-tour-vocabmaster-android.log|$RUNS_DIR/vocabmaster-android"
)

python3 - "$OUT" "$RUNS_DIR" "${REPOS[@]}" <<'PYEOF'
import json, os, sys
from datetime import datetime

out_path = sys.argv[1]
runs_dir = sys.argv[2]
repo_specs = sys.argv[3:]

def fmt_secs(s):
  if not s: return "—"
  m = s // 60
  rem = s % 60
  return f"{m}m{rem:02d}s"

def read_json(path):
  try:
    with open(path) as f: return json.load(f)
  except FileNotFoundError: return None
  except json.JSONDecodeError as e: return {"_err": f"JSON parse: {e}"}
  except Exception as e: return {"_err": str(e)}

def read_clone_summary(clone_path):
  p = os.path.join(clone_path, "summary.json")
  s = read_json(p)
  if not s or "_err" in (s or {}): return None
  return s

def read_clone_memory(clone_path):
  p = os.path.join(clone_path, ".swarm-memory.jsonl")
  if not os.path.exists(p): return []
  out = []
  try:
    with open(p) as f:
      for line in f:
        line = line.strip()
        if not line: continue
        try: out.append(json.loads(line))
        except: pass
  except: pass
  return out

lines = []
lines.append("# Smoke tour comparison")
lines.append(f"_Generated {datetime.now().isoformat(timespec='seconds')}_")
lines.append("")
lines.append("Generated by `scripts/smoke-tour-compare.sh`. Re-run any time to refresh.")
lines.append("")

for spec in repo_specs:
  label, progress_path, log_path, clone_path = spec.split("|")
  lines.append(f"## {label}")
  lines.append(f"- Clone path: `{clone_path}`")
  lines.append(f"- Progress checkpoint: `{progress_path}`")
  lines.append(f"- Log file: `{log_path}`")

  prog = read_json(progress_path)
  if prog is None:
    lines.append(f"- **Status: not started yet** (no checkpoint file)")
    lines.append("")
    continue
  if "_err" in (prog or {}):
    lines.append(f"- **Checkpoint error**: {prog['_err']}")
    lines.append("")
    continue

  done = sum(1 for r in prog if r.get("phase") in ("completed", "stopped", "early-stop") or r.get("status") == "start_failed")
  total = len(prog)
  lines.append(f"- **Progress: {done}/{total or '?'} preset runs recorded**")
  lines.append("")

  if not prog:
    lines.append("_(no rows yet)_\n")
    continue

  lines.append("| # | Preset | Agents | Rounds | Phase | Wall | RunID | Quota | Notes |")
  lines.append("|---|---|---|---|---|---|---|---|---|")
  for i, row in enumerate(prog, 1):
    preset = row.get("preset", "?")
    agents = row.get("agents", "—")
    rounds = row.get("rounds", "—")
    phase = row.get("phase") or row.get("status", "?")
    wall = fmt_secs(row.get("wall_s", 0))
    run_id = (row.get("runId") or "")[:8]
    quota = row.get("quota") or "—"
    notes = ""
    if row.get("status") == "start_failed":
      notes = (row.get("reason") or "")[:80]
    lines.append(f"| {i} | `{preset}` | {agents} | {rounds} | {phase} | {wall} | `{run_id}` | {quota} | {notes} |")
  lines.append("")

  s = read_clone_summary(clone_path)
  if s:
    lines.append("### Latest summary.json on this clone")
    lines.append(f"- Stop reason: `{s.get('stopReason','?')}`{' · ' + s.get('stopDetail','') if s.get('stopDetail') else ''}")
    lines.append(f"- Wall: {fmt_secs(round(s.get('wallClockMs',0)/1000))} · Files changed: {s.get('filesChanged','?')} · Commits: {s.get('commits','?')}")
    if s.get("agents"):
      lines.append(f"- Per-agent turns: " + ", ".join(f"a{a.get('agentIndex')}={a.get('turnsTaken',0)}" for a in s["agents"]))
    lines.append("")
  mem = read_clone_memory(clone_path)
  if mem:
    lines.append("### Persistent memory (.swarm-memory.jsonl)")
    lines.append(f"_{len(mem)} entries on file — most recent first_")
    lines.append("")
    for e in sorted(mem, key=lambda x: x.get("ts",0), reverse=True)[:5]:
      ts = datetime.fromtimestamp(e.get("ts",0)/1000).isoformat(timespec="minutes")
      lines.append(f"- **{ts}** · runId `{e.get('runId','?')[:8]}` · tier {e.get('tier','?')} · {e.get('commits','?')} commits")
      for lesson in e.get("lessons", []):
        lines.append(f"    - {lesson}")
    lines.append("")

with open(out_path, "w") as f:
  f.write("\n".join(lines))
print(f"Wrote {out_path}", file=sys.stderr)
PYEOF
echo "Done. Output: $OUT"
