// AUTO-GENERATED by server/scripts/discover-runner-fields.ts
// DO NOT EDIT MANUALLY. Regenerate after adding/removing properties
// on BlackboardRunner:
//   npx tsx server/scripts/discover-runner-fields.ts > server/src/swarm/blackboard/runnerContextTypes.ts

/** Union of all BlackboardRunner properties referenced by context builders.
 *  Replaces the unsafe `BlackboardRunnerFields = any` escape hatch.
 *  125 properties discovered across 11 contexts. */
export interface BlackboardRunnerFields {
  _wasDrained: any;
  active: any;
  activeAborts: any;
  adaptiveHysteresis: any;
  adaptiveScaleInFlight: any;
  adaptiveWatchdog: any;
  agentRoster: any;
  allCriteriaMet: any;
  allCriteriaResolved: any;
  allCriteriaResolvedSnapshot: any;
  appendAgent: any;
  appendSystem: any;
  attemptsPerAgent: any;
  auditInvocations: any;
  auditor: any;
  boardBroadcaster: any;
  boardCounts: any;
  boardGetTodo: any;
  boardListTodos: any;
  brainPromptFn: any;
  buildReflectionContext: any;
  buildSeed: any;
  capWatchdog: any;
  checkAndApplyCaps: any;
  cloneContract: any;
  cloneStateForStatus: any;
  commitsByCriterion: any;
  commitsPerAgent: any;
  completionDetail: any;
  consecutiveLoopDetections: any;
  consecutiveStuckCycles: any;
  contract: any;
  currentTier: any;
  directiveWithAmendments: any;
  discoverLocalOllamaTags: any;
  drainStartedAt: any;
  drainWatcherTimer: any;
  emitAgentState: any;
  enqueueReplan: any;
  errorTracker: any;
  extractText: any;
  failoverState: any;
  fileCommitCounts: any;
  findings: any;
  flushStateWrite: any;
  hypothesisDeferralTimestamps: any;
  hypothesisGroupAborts: any;
  isOverWallClockCap: any;
  isRunning: any;
  jsonRepairsPerAgent: any;
  lastLoopWarningAtTurn: any;
  lastMemoryPressureLevel: any;
  latenciesPerAgent: any;
  lifecycleState: any;
  linesAddedPerAgent: any;
  linesRemovedPerAgent: any;
  localOllamaTags: any;
  loopDetectionsToHalt: any;
  markPlannerStatus: any;
  maxAuditInvocations: any;
  maxTrackedErrors: any;
  maybeSettleHypothesisGroup: any;
  memoryPaused: any;
  opts: any;
  pauseProbeAttempt: any;
  pauseProbeTimer: any;
  pauseStartedAt: any;
  paused: any;
  phase: any;
  planner: any;
  priorSnapshot: any;
  promptAgent: any;
  promptErrorsPerAgent: any;
  promptPlannerSafely: any;
  promptTokensPerAgent: any;
  readExpectedFiles: any;
  recentLatencySamples: any;
  recordError: any;
  rejectedAttemptsPerAgent: any;
  replanPending: any;
  replanRunning: any;
  responseTokensPerAgent: any;
  retriesPerAgent: any;
  round: any;
  runAuditedExecution: any;
  runAuditor: any;
  runAutoRollbacks: any;
  runBootedAt: any;
  runFirstPassContractOrchestrator: any;
  runPlanner: any;
  runPlannerFallbackForUnmetCriteria: any;
  runStartedAt: any;
  runWorkers: any;
  scheduleStateWrite: any;
  setPhase: any;
  staleEventCount: any;
  startAdaptiveWorkerWatchdog: any;
  startCapWatchdog: any;
  startQueueReaper: any;
  startReplanWatcher: any;
  stateSnapshotScheduler: any;
  stop: any;
  stopCapWatchdog: any;
  stopQueueReaper: any;
  stopReplanWatcher: any;
  subscriberPaused: any;
  terminationReason: any;
  tickAccumulator: any;
  tierHistory: any;
  tierStartedAt: any;
  tierUpFailures: any;
  tiersCompleted: any;
  todoQueue: any;
  tokenBaselineForRun: any;
  totalPausedMs: any;
  transcript: any;
  tryResumeContract: any;
  turnsPerAgent: any;
  v2Observer: any;
  workerPool: any;
  workerRoles: any;
  wrappers: any;
  writeBlackboardDeliverable: any;
  writeCrashSnapshot: any;
  writeRunSummary: any;
  interactionTracker: any;
  exceptionCollector: any;
  initBrainOverseer: any;
}

/** Properties accessed by adaptiveWatchdogContext(). 8 properties. */export interface AdaptiveWatchdogFields {
  active: any;
  adaptiveHysteresis: any;
  adaptiveScaleInFlight: any;
  adaptiveWatchdog: any;
  appendSystem: any;
  lifecycleState: any;
  opts: any;
  todoQueue: any;
}

/** Properties accessed by auditorContext(). 19 properties. */export interface AuditorFields {
  active: any;
  allCriteriaResolvedSnapshot: any;
  appendAgent: any;
  appendSystem: any;
  auditInvocations: any;
  auditor: any;
  boardListTodos: any;
  brainPromptFn: any;
  cloneContract: any;
  contract: any;
  findings: any;
  lifecycleState: any;
  maxAuditInvocations: any;
  opts: any;
  promptPlannerSafely: any;
  readExpectedFiles: any;
  transcript: any;
  v2Observer: any;
  wrappers: any;
}

/** Properties accessed by capContext(). 22 properties. */export interface CapFields {
  active: any;
  activeAborts: any;
  appendSystem: any;
  boardCounts: any;
  capWatchdog: any;
  lastMemoryPressureLevel: any;
  lifecycleState: any;
  memoryPaused: any;
  pauseProbeAttempt: any;
  pauseProbeTimer: any;
  pauseStartedAt: any;
  paused: any;
  planner: any;
  recordError: any;
  runStartedAt: any;
  setPhase: any;
  subscriberPaused: any;
  terminationReason: any;
  tickAccumulator: any;
  tokenBaselineForRun: any;
  totalPausedMs: any;
  v2Observer: any;
}

/** Properties accessed by contractContext(). 17 properties. */export interface ContractFields {
  active: any;
  appendAgent: any;
  appendSystem: any;
  brainPromptFn: any;
  contract: any;
  currentTier: any;
  findings: any;
  lifecycleState: any;
  opts: any;
  priorSnapshot: any;
  promptAgent: any;
  promptPlannerSafely: any;
  scheduleStateWrite: any;
  tierHistory: any;
  tierStartedAt: any;
  tiersCompleted: any;
  v2Observer: any;
}

/** Properties accessed by lifecycleContext(). 92 properties. */export interface LifecycleFields {
  _wasDrained: any;
  active: any;
  activeAborts: any;
  agentRoster: any;
  allCriteriaMet: any;
  allCriteriaResolved: any;
  appendSystem: any;
  attemptsPerAgent: any;
  auditInvocations: any;
  auditor: any;
  boardBroadcaster: any;
  boardCounts: any;
  buildReflectionContext: any;
  buildSeed: any;
  cloneStateForStatus: any;
  commitsPerAgent: any;
  completionDetail: any;
  consecutiveLoopDetections: any;
  contract: any;
  currentTier: any;
  discoverLocalOllamaTags: any;
  drainStartedAt: any;
  drainWatcherTimer: any;
  errorTracker: any;
  failoverState: any;
  fileCommitCounts: any;
  findings: any;
  flushStateWrite: any;
  hypothesisDeferralTimestamps: any;
  hypothesisGroupAborts: any;
  isOverWallClockCap: any;
  isRunning: any;
  jsonRepairsPerAgent: any;
  lastLoopWarningAtTurn: any;
  lastMemoryPressureLevel: any;
  latenciesPerAgent: any;
  lifecycleState: any;
  linesAddedPerAgent: any;
  linesRemovedPerAgent: any;
  localOllamaTags: any;
  markPlannerStatus: any;
  maxAuditInvocations: any;
  memoryPaused: any;
  opts: any;
  pauseProbeTimer: any;
  pauseStartedAt: any;
  paused: any;
  planner: any;
  priorSnapshot: any;
  promptErrorsPerAgent: any;
  promptTokensPerAgent: any;
  recordError: any;
  rejectedAttemptsPerAgent: any;
  responseTokensPerAgent: any;
  retriesPerAgent: any;
  round: any;
  runAuditedExecution: any;
  runAuditor: any;
  runAutoRollbacks: any;
  runBootedAt: any;
  runFirstPassContractOrchestrator: any;
  runPlanner: any;
  runStartedAt: any;
  setPhase: any;
  staleEventCount: any;
  startAdaptiveWorkerWatchdog: any;
  startCapWatchdog: any;
  startQueueReaper: any;
  startReplanWatcher: any;
  stateSnapshotScheduler: any;
  stop: any;
  stopCapWatchdog: any;
  stopQueueReaper: any;
  stopReplanWatcher: any;
  subscriberPaused: any;
  terminationReason: any;
  tickAccumulator: any;
  tierHistory: any;
  tierStartedAt: any;
  tierUpFailures: any;
  tiersCompleted: any;
  todoQueue: any;
  tokenBaselineForRun: any;
  totalPausedMs: any;
  transcript: any;
  tryResumeContract: any;
  turnsPerAgent: any;
  v2Observer: any;
  workerRoles: any;
  writeBlackboardDeliverable: any;
  writeCrashSnapshot: any;
  writeRunSummary: any;
}

/** Properties accessed by plannerContext(). 14 properties. */export interface PlannerFields {
  active: any;
  appendAgent: any;
  appendSystem: any;
  boardCounts: any;
  brainPromptFn: any;
  buildSeed: any;
  contract: any;
  findings: any;
  hypothesisGroupAborts: any;
  lifecycleState: any;
  opts: any;
  promptPlannerSafely: any;
  v2Observer: any;
  wrappers: any;
}

/** Properties accessed by promptContext(). 21 properties. */export interface PromptFields {
  active: any;
  activeAborts: any;
  appendSystem: any;
  attemptsPerAgent: any;
  consecutiveLoopDetections: any;
  emitAgentState: any;
  errorTracker: any;
  extractText: any;
  failoverState: any;
  lastLoopWarningAtTurn: any;
  latenciesPerAgent: any;
  lifecycleState: any;
  localOllamaTags: any;
  maxTrackedErrors: any;
  opts: any;
  promptTokensPerAgent: any;
  recentLatencySamples: any;
  responseTokensPerAgent: any;
  retriesPerAgent: any;
  terminationReason: any;
  turnsPerAgent: any;
}

/** Properties accessed by replanContext(). 14 properties. */export interface ReplanFields {
  appendAgent: any;
  appendSystem: any;
  boardGetTodo: any;
  boardListTodos: any;
  brainPromptFn: any;
  checkAndApplyCaps: any;
  lifecycleState: any;
  opts: any;
  planner: any;
  promptPlannerSafely: any;
  readExpectedFiles: any;
  replanPending: any;
  replanRunning: any;
  wrappers: any;
}

/** Properties accessed by tierContext(). 26 properties. */export interface TierFields {
  active: any;
  appendAgent: any;
  appendSystem: any;
  auditInvocations: any;
  boardCounts: any;
  boardListTodos: any;
  checkAndApplyCaps: any;
  cloneContract: any;
  completionDetail: any;
  consecutiveStuckCycles: any;
  contract: any;
  currentTier: any;
  directiveWithAmendments: any;
  findings: any;
  lifecycleState: any;
  opts: any;
  promptPlannerSafely: any;
  runAuditor: any;
  runPlannerFallbackForUnmetCriteria: any;
  runWorkers: any;
  scheduleStateWrite: any;
  tierHistory: any;
  tierStartedAt: any;
  tierUpFailures: any;
  tiersCompleted: any;
  v2Observer: any;
}

/** Properties accessed by utilContext(). 16 properties. */export interface RunnerUtilFields {
  active: any;
  activeAborts: any;
  appendSystem: any;
  consecutiveLoopDetections: any;
  findings: any;
  lastLoopWarningAtTurn: any;
  lifecycleState: any;
  loopDetectionsToHalt: any;
  opts: any;
  phase: any;
  round: any;
  runStartedAt: any;
  scheduleStateWrite: any;
  terminationReason: any;
  todoQueue: any;
  transcript: any;
}

/** Properties accessed by workerContext(). 34 properties. */export interface WorkerFields {
  active: any;
  appendAgent: any;
  appendSystem: any;
  auditor: any;
  boardCounts: any;
  brainPromptFn: any;
  checkAndApplyCaps: any;
  commitsByCriterion: any;
  commitsPerAgent: any;
  emitAgentState: any;
  enqueueReplan: any;
  fileCommitCounts: any;
  hypothesisDeferralTimestamps: any;
  hypothesisGroupAborts: any;
  jsonRepairsPerAgent: any;
  lifecycleState: any;
  linesAddedPerAgent: any;
  linesRemovedPerAgent: any;
  maybeSettleHypothesisGroup: any;
  memoryPaused: any;
  opts: any;
  paused: any;
  promptAgent: any;
  promptErrorsPerAgent: any;
  readExpectedFiles: any;
  rejectedAttemptsPerAgent: any;
  replanPending: any;
  replanRunning: any;
  staleEventCount: any;
  subscriberPaused: any;
  todoQueue: any;
  workerPool: any;
  workerRoles: any;
  wrappers: any;
}


