#!/usr/bin/env node
// Discover BlackboardRunner properties per context builder.
// Outputs generated runnerContextTypes.ts (stdout). With --check,
// exits 1 if property count drifts below 100.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const srcPath = path.resolve(here, "..", "src", "swarm", "blackboard", "contextBuilders.ts");
const lines = fs.readFileSync(srcPath, "utf8").split("\n");

// Find all "export function" lines that define a context builder.
// These accept r: BlackboardRunnerFields.
const fnRe = /^export function (\w+(?:Context|Ctx))\(r:\s*BlackboardRunnerFields/;
const fnLines: Array<{ idx: number; name: string }> = [];
for (let i = 0; i < lines.length; i++) {
  const m = lines[i].match(fnRe);
  if (m) {
    fnLines.push({ idx: i, name: m[1] });
  }
}

// Per-context property sets
const perContext: Record<string, Set<string>> = {};

for (let fi = 0; fi < fnLines.length; fi++) {
  const { idx: startIdx, name } = fnLines[fi];
  const contextName = name.replace(/Ctx$/, "").replace(/Context$/, "");

  // The function body starts at startIdx and runs to the next
  // fnLines[fi+1].idx, or end of file.
  const endIdx = fi + 1 < fnLines.length ? fnLines[fi + 1].idx : lines.length;

  const props = new Set<string>();
  for (let i = startIdx; i < endIdx; i++) {
    const re = /\br\.(\w+)/g;
    let m;
    while ((m = re.exec(lines[i])) !== null) {
      props.add(m[1]);
    }
  }

  if (props.size > 0) {
    perContext[contextName] = props;
  }
}

// All unique
const all = new Set(Object.values(perContext).flatMap((s) => [...s]));

if (process.argv.includes("--check")) {
  if (all.size < 100) {
    console.error(`CI check failed: only ${all.size} unique properties (expected 120+).`);
    process.exit(1);
  }
  console.log(`${all.size} unique across ${Object.keys(perContext).length} contexts.`);
  process.exit(0);
}

// --- Generate TypeScript file ---
const interfaceNames: Record<string, string> = {
  "util": "RunnerUtilFields",
  "lifecycle": "LifecycleFields",
  "contract": "ContractFields",
  "tier": "TierFields",
  "planner": "PlannerFields",
  "worker": "WorkerFields",
  "prompt": "PromptFields",
  "cap": "CapFields",
  "replan": "ReplanFields",
  "auditor": "AuditorFields",
  "adaptiveWatchdog": "AdaptiveWatchdogFields",
};

const out: string[] = [
  `// AUTO-GENERATED by server/scripts/discover-runner-fields.ts
// DO NOT EDIT MANUALLY. Regenerate after adding/removing properties
// on BlackboardRunner:
//   npx tsx server/scripts/discover-runner-fields.ts > server/src/swarm/blackboard/runnerContextTypes.ts

/** Union of all BlackboardRunner properties referenced by context builders.
 *  Replaces the unsafe \`BlackboardRunnerFields = any\` escape hatch.
 *  ${all.size} properties discovered across ${Object.keys(perContext).length} contexts. */
export interface BlackboardRunnerFields {\n`,
];

for (const prop of [...all].sort()) {
  out.push(`  ${prop}: any;`);
  out.push("\n");
}
out.push("}\n\n");

// Per-context subtypes
for (const [ctx, iface] of Object.entries(interfaceNames).sort(([a], [b]) => a.localeCompare(b))) {
  const props = perContext[ctx];
  if (!props || props.size === 0) continue;
  const sorted = [...props].sort();

  out.push(`/** Properties accessed by ${ctx}Context(). ${sorted.length} properties. */`);
  out.push(`export interface ${iface} {\n`);
  for (const p of sorted) {
    out.push(`  ${p}: any;`);
    out.push("\n");
  }
  out.push("}\n\n");
}

console.log(out.join(""));
